server:
  port: 8080

spring:
  application:
    name: load-balancer

load-balancer:
  algorithm: "LEAST_CONNECTIONS"
  app-server-details:
    - url: "https://ip-address-1.com"
      health-check-url: "https://ip-address-1.com/health"
    - url: "https://ip-address-2.com"
      health-check-url: "https://ip-address-2.com/health"

mock:
  enabled: "true"